version: '2'
config: {  }
environment:
  BUILD_IMAGE: 'maven:3.6-jdk-11'
jobs:
  build_docker:
    steps:
      - build_image
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: danalytics
          workload: flink-kubernetes-operator
          argocd_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-data-platform-prod
          namespace: default
          workload: flink-kubernetes-operator
          argocd_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - dev
                - main
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - dev
                - main
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - dev
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - main
deployment_config:
  dev:
    workloadType: Deployment
    serviceAccount: default
    replicaCount: 1
    strategy:
      type: Recreate
    spec:
      securityContext:
        runAsGroup: 9999
        runAsUser: 9999
    image:
      imagePullPolicy: IfNotPresent
    command:
      - /docker-entrypoint.sh
      - operator
    ingress:
      service:
        enabled: false
      enabled: true
      hosts:
          paths:
            - port: 8085
              path: /
    envVars:
      OPERATOR_NAMESPACE: default
      OPERATOR_NAME: flink-kubernetes-operator
      FLINK_CONF_DIR: /opt/flink/conf
      FLINK_PLUGINS_DIR: /opt/flink/plugins
      LOG_CONFIG: -Dlog4j.configurationFile=/opt/flink/conf/log4j-operator.properties
    volumeMounts:
      - name: flink-operator-config-volume
        mountPath: /opt/flink/conf/flink-conf.yaml
        subPath: flink-conf.yaml
      - name: flink-operator-config-volume
        mountPath: /opt/flink/conf/log4j-operator.properties
        subPath: log4j-operator.properties
      - name: flink-operator-config-volume
        mountPath: /opt/flink/conf/log4j-console.properties
        subPath: log4j-console.properties
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      httpGet:
        path: /
        port: 8085
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
      httpGet:
        path: /
        port: 8085
    volumes:
      - name: flink-operator-config-volume
        configMap:
          name: flink-operator-config
          items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: log4j-operator.properties
              path: log4j-operator.properties
            - key: log4j-console.properties
              path: log4j-console.properties